### ISSUE TITLE
build failing (pandoc / pypandoc related?)

### ISSUE THREAD

**Issue by gingerlime** [Alephbet/gimel#11]
https://travis-ci.org/Alephbet/gimel/jobs/136246047

not entirely sure why, because nothing related has changed. Running `python setup.py check -m -r -s` locally seems to work ok if pandoc is installed...

@Azd325 perhaps you can help?

**Comment by Azd325** [comment]
Yep, this is pandoc related because the version of the travis ubuntu version is to old for the syntax. 
I tried already on another branch to fix this with a new version of pandoc but to good result.
It give me some PATH issues. I tried also to install it over cabal from haskell.

Maybe we take the syntax check out of the tox check!

**Comment by gingerlime** [comment]
Yes, if it's so fragile, we might as well take it out. Or I'll have to live with an `rst` readme :)

**Comment by Azd325** [comment]
For the moment it would be fine to take the check out on travis but keep it
for local testing.
Travis only test the environment what are defined in the travis.yml so it
would be fine if we split it in a  manifest and a Readme check? And we will
only check the manifest on travis...

gingerlime notifications@github.com schrieb am Mi., 8. Juni 2016, 22:05:
